# Generated by Django 3.2.9 on 2021-11-23 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('qty', models.IntegerField()),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('mu', 'Music'), ('mo', 'Movie'), ('ga', 'Game')], max_length=2)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(default='menu/food.jpg', upload_to='menu')),
            ],
        ),
    ]
