# Generated by Django 3.2.9 on 2021-11-23 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_id',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.CharField(default=None, max_length=255, primary_key=True, serialize=False),
        ),
    ]
