# Generated by Django 3.2.9 on 2021-11-23 08:51

from django.db import migrations, models
import transaction.models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_auto_20211123_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.CharField(default=transaction.models.generate_pk, max_length=255, primary_key=True, serialize=False),
        ),
    ]
