# Generated by Django 3.2.9 on 2021-11-29 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_post_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
